/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LockinImport } from './routes/lockin'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LockinRoute = LockinImport.update({
  id: '/lockin',
  path: '/lockin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lockin': {
      id: '/lockin'
      path: '/lockin'
      fullPath: '/lockin'
      preLoaderRoute: typeof LockinImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lockin': typeof LockinRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lockin': typeof LockinRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/lockin': typeof LockinRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lockin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lockin'
  id: '__root__' | '/' | '/lockin'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LockinRoute: typeof LockinRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LockinRoute: LockinRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lockin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/lockin": {
      "filePath": "lockin.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
